APPLICATION_ID: vkapp
service_description:
  name: customer-service
  version: 0.0.1
cse:
#  service:
#    registry:
#      address: http://127.0.0.1:30100
#      instance:
#        watch: false
#  config:
#    client:
#      refreshMode: 1
  service:
    registry:
      address: https://cse.cn-north-1.myhwclouds.com:443
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-north-1.myhwclouds.com:443
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-north-1.myhwclouds.com:443
  credentials:
    accessKey: 670WKUPXTZE3Z8Y0N8VR
    secretKey: YGGzjw6ommpqbA7AaeaxUOlVennIccER6l8U5jDZ
    akskCustomCipher: default
    
  highway:
    address: 0.0.0.0:9093
    server:
      thread-count: 10